FROM alpine:latest
ARG ENV=prod
COPY cron/crontab.${ENV} /etc/crontabs/root
COPY cron/takeasweater.sh /takeasweater.sh
RUN apk update && apk add bash && apk add curl
RUN chmod 0644 /etc/crontabs/root
RUN crontab /etc/crontabs/root
CMD ["crond","-f", "-L", "/dev/stdout"]